blueprint:
  name: nightlight_controller
  domain: automation
  input:
    target:
      selector:
        entity:
          domain: light

mode: restart
variables:
  target: !input target

trigger:
  - platform: state
    entity_id: !input target
    to: "off"

action:
  - variables:
      first_target: |
        {%- set entity_id = state_attr(target,'entity_id') -%}
        {%- if entity_id -%}
        {{- entity_id[0] -}}
        {%- else -%}
        {{- target -}}
        {%- endif -%}

  - service: light.turn_on
    data:
      entity_id: "{{ first_target }}"
      transition: 0.1
      brightness: "1"
      hs_color: [0,100]
